### ISSUE TITLE
Projects disappeared

### ISSUE THREAD

**Issue by benfredwells** [googlearchive/code-editor-app#6]
I was using code editor nicely yesterday but today my projects have disappeared, and I can't create any new projects.

Chrome version is Chrome/29.0.1535.3  (X11; Linux x86_64)

**Comment by SOEL86** [comment]
I have the same issue on Windows 7, Windows 8 and Chromium OS.

**Comment by kinu** [comment]
Hi, you might be hitting some SyncFS bug, which is not stable yet with directory operation support (we're trying hard to make it stable).  Is it possible to open chrome://syncfs-internals/ and see what's shown there after you try to create a new project?  It might help us to debug. Thanks,

**Comment by bisraelsen** [comment]
I am having a similar problem. Projects dissapear, then re-appear. etc.... Here is part of my chrome://syncfs-internals/  file. I am new to github so I am not sure how to attach the whole file. If you need it let me know.

This is what it looks like unresolved.

<pre><code>
2013-08-24T23:19:20.643 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:20.644 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:22.382 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:22.382 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:23.817 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:23.818 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:25.011 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:25.012 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:26.375 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:26.376 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:27.809 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:27.810 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:29.241 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:29.242 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:30.685 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:30.686 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:31.918 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:31.919 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T23:19:33.241 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T23:19:33.242 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
</code></pre>

Here is where the problem was resolved. Not sure exactly what I did to get it going. I was restarting a few things. I'll try to pay more attention next time.

<pre><code>
2013-08-24T10:09:57.770 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T10:09:57.771 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T10:09:59.150 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T10:09:59.150 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T10:10:00.378 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T10:10:00.378 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T10:10:01.689 [VERBOSE] Resolving conflict for local sync: filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs): LOCAL WIN
2013-08-24T10:10:07.156 [VERBOSE] ApplyLocalChange for filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs) local_change:ADD_OR_UPDATE:FILE ===> UPDATE_FILE
2013-08-24T10:10:17.273 [INFO] Service state changed: 0->1: Network or temporary service error.
2013-08-24T10:10:17.273 [INFO] OnRemoteServiceStateChanged: 1 Network or temporary service error.
2013-08-24T10:10:17.273 [VERBOSE] ProcessLocalChange finished with status=-105 (Sync: retry to synchronize.) for url=filesystem:chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/external/syncfs/prefs (Syncable@syncfs:prefs)
2013-08-24T10:10:17.274 [VERBOSE] Calling ProcessLocalChange for LocalSync
2013-08-24T10:10:17.278 [VERBOSE] ProcessLocalChange finished with status=-104 (Sync: no change to synchronize.) for url=invalid filesystem: URL
2013-08-24T10:10:19.250 [INFO] Service state changed: 1->0:
2013-08-24T10:10:19.250 [INFO] OnRemoteServiceStateChanged: 0
2013-08-24T10:10:19.250 [VERBOSE] Calling ProcessLocalChange for LocalSync
2013-08-24T10:10:19.252 [VERBOSE] ProcessLocalChange finished with status=-104 (Sync: no change to synchronize.) for url=invalid filesystem: URL
2013-08-24T10:10:19.596 [VERBOSE] Start batch sync for: chrome-extension://gonnpeheodhmhdjiimoiheniambmdcco/
2013-08-24T10:10:51.552 [VERBOSE] Calling ProcessLocalChange for LocalSync
2013-08-24T10:10:52.057 [VERBOSE] ProcessLocalChange finished with status=-104 (Sync: no change to synchronize.) for url=invalid filesystem: URL
2013-08-24T10:11:04.267 [VERBOSE] Calling ProcessLocalChange for LocalSync
2013-08-24T10:11:04.268 [VERBOSE] ProcessLocalChange finished with status=-104 (Sync: no change to synchronize.) for url=invalid filesystem: URL
2013-08-24T10:11:57.403 [VERBOSE] Calling ProcessLocalChange for LocalSync
2013-08-24T10:11:57.404 [VERBOSE] ProcessLocalChange finished with status=-104 (Sync: no change to synchronize.) for url=invalid filesystem: URL
2013-08-24T10:14:10.380 [VERBOSE] Calling ProcessLocalChange for LocalSync
</code></pre>

**Comment by kinu** [comment]
@bisraelsen Thanks for the log, we found that the API's having trouble in uploading a local update (it keeps failing) due to an incompatible change on the server-side.  It's going to be resolved soon (on Mon or Tue at worst), but until then it may be in an unstable state.  Sorry for the inconveniences.

**Comment by bisraelsen** [comment]
Glad to be of some assistance. Just excited to be able to use this app. Thanks!

Also, I noticed that if I just left the computer sitting the problem would resolve itself although it would take 10-15 minutes and was very unpredictable. Nothing I did seemed to affect the problem.

**Comment by kinu** [comment]
It's been pretty unstable for longer than we expected, but the server-side issue has been finally resolved and it should be working now.  Sorry for the trouble.

**Comment by dinhvh** [comment]
It's still happening for me:
It usually reproduces when I open the application, create a project, add some files to it.
Then, close the window.
I'll reload it using chrome://extensions (or Apps Developer Tools).
When I reopen code editor, the files of my projects disappear and sometimes, all the projects also disappeared.

**Comment by bisraelsen** [comment]
As far as I can tell this issue is resolved. I do not see the problem any longer.

**Comment by dinhvh** [comment]
In code_editor_dev branch, I added some visual feedback when SyncFS is not ready. It really improves the behavior.
